version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: blogging_mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: blogging_db
    volumes:
      - mongodb_data:/data/db

  api:
    build: .
    container_name: blogging_api
    ports:
      - "3000:3000"
    environment:
      MONGODB_URI: mongodb://mongodb:27017
      DB_NAME: blogging_db
      JWT_SECRET: n4R7pDk8qZ1sW5xY2vB3cV7tJ0mN8fH4K928
      NODE_ENV: production
      ADMIN_EMAIL: admin@example.com      
      ADMIN_PASSWORD: Admin123!          
      FRONTEND_URL: http://localhost:3000 
    depends_on:
      - mongodb

volumes:
  mongodb_data: