version: '3.8'

services:
  api:
    build: .
    container_name: blogging_api
    ports:
      - "3000:3000"
    environment:
      MONGODB_URI: ${MONGODB_URI}  
      DB_NAME: ${DB_NAME}          
      JWT_SECRET: n4R7pDk8qZ1sW5xY2vB3cV7tJ0mN8fH4K928
      NODE_ENV: production
      ADMIN_EMAIL: admin@example.com      
      ADMIN_PASSWORD: Admin123!          
      FRONTEND_URL: http://localhost:3000
    restart: unless-stopped
